version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: appointments-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432" 

  spring-boot-app:
    image: appointments-spring-boot-app
    container_name: appointments-spring-boot-app
    restart: unless-stopped
    ports:
      - "8080:8080" 
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin